openapi: 3.0.3
info:
  title: RPG API
  version: 1.0.0
  description: Provides api views for RPG characters, classes and items.
paths:
  /api/v1/characters/:
    get:
      operationId: root_list
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Character'
          description: ''
    post:
      operationId: root_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Character'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Character'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Character'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
          description: ''
  /api/v1/characters/{id}/:
    get:
      operationId: root_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this character.
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
          description: ''
    put:
      operationId: root_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this character.
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Character'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Character'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Character'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
          description: ''
    patch:
      operationId: root_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this character.
        required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCharacter'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCharacter'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCharacter'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
          description: ''
    delete:
      operationId: root_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this character.
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Character:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        desc:
          type: string
          nullable: true
          maxLength: 255
        exp:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
      required:
      - id
      - name
    PatchedCharacter:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        desc:
          type: string
          nullable: true
          maxLength: 255
        exp:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
