# Generated by Django 5.2.7 on 2025-11-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('exp', models.IntegerField(default=1, editable=False)),
            ],
        ),
    ]
