# Generated by Django 5.2.7 on 2025-11-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=1),
        ),
    ]
